# Generated by Django 3.1.1 on 2020-10-22 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_user_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
