# Generated by Django 3.1.1 on 2020-10-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0003_auto_20201002_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='height',
            field=models.IntegerField(max_length=170),
        ),
        migrations.AlterField(
            model_name='friend',
            name='place',
            field=models.CharField(max_length=100),
        ),
    ]
