# Generated by Django 3.1.1 on 2020-10-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0004_auto_20201002_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='introduce',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
