# Generated by Django 3.1.1 on 2020-10-03 05:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0005_auto_20201003_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='height',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(150.0), django.core.validators.MaxValueValidator(169.9)]),
        ),
    ]
