# Generated by Django 3.1.1 on 2020-10-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0006_auto_20201003_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='gender',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
