# Generated by Django 3.1.1 on 2020-10-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0007_friend_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='gender',
            field=models.IntegerField(choices=[(1, '男性'), (2, '女性')], verbose_name='性別'),
        ),
    ]
