# Generated by Django 3.1.1 on 2020-10-03 14:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0008_auto_20201003_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sns.group', verbose_name='グループ'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='height',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(150.0), django.core.validators.MaxValueValidator(169.9)], verbose_name='身長'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='introduce',
            field=models.CharField(max_length=250, null=True, verbose_name='自己紹介'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='place',
            field=models.CharField(max_length=100, verbose_name='居住地'),
        ),
    ]
