# Generated by Django 3.1.1 on 2020-10-03 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0009_auto_20201003_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='height',
        ),
    ]
