# Generated by Django 3.1.1 on 2020-10-03 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0010_remove_friend_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='height',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(150.0), django.core.validators.MaxValueValidator(169.9)], verbose_name='身長'),
            preserve_default=False,
        ),
    ]
