# Generated by Django 3.1.1 on 2020-10-04 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0011_friend_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='height',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(169.9), django.core.validators.MinValueValidator(150.0)], verbose_name='身長'),
        ),
    ]
