# Generated by Django 3.1.1 on 2020-10-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0012_auto_20201004_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='生年月日'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='height',
            field=models.FloatField(verbose_name='身長'),
        ),
    ]
