from .base import *

DEBUG = False

DATABASES = {
    'default': env.db()
}

SECRET_KEY = os.environ['SECRET_KEY']
EMAIL_HOST_PASSWORD = os.environ['EMAIL_HOST_PASSWORD']
SOCIAL_AUTH_TWITTER_KEY = os.environ['SOCIAL_AUTH_TWITTER_KEY']
SOCIAL_AUTH_TWITTER_SECRET = os.environ['SOCIAL_AUTH_TWITTER_SECRET']
AUTHENTICATION_TOKEN = os.environ['AUTHENTICATION_TOKEN']
AUTHENTICATION_SECRET = os.environ['AUTHENTICATION_SECRET']
django_heroku.settings(locals())